### PR TITLE
Remove sre02; add master on sre03; add etcd on sre04

### PR DESCRIPTION
**Pull request by gh-lbulawa**
All info is available in the ticket https://guardanthealth.atlassian.net/browse/BIK8S-119

### CODE REVIEW

**Comment by gh-amaroo** [comment]
Are you sure this will work? Have you made sure we meet these conditions: 
https://github.com/kubernetes-sigs/kubespray/blob/master/docs/recover-control-plane.md
https://github.com/kubernetes-sigs/kubespray/blob/master/docs/nodes.md

Neither ticket nor this PR has details of how this can be done.

**Comment by gh-lbulawa** [comment]
> Are you sure this will work? Have you made sure we meet these conditions:
> https://github.com/kubernetes-sigs/kubespray/blob/master/docs/recover-control-plane.md
> https://github.com/kubernetes-sigs/kubespray/blob/master/docs/nodes.md
> 
> Neither ticket nor this PR has details of how this can be done.

Well, I'll be sure after running this :)
I went through the docs you have linked and I'm pretty sure that the only important part in "recover control plane" scenario is running `cluster.yaml` playbook, the rest are `kubectl` and `etcdctl` operations which does not seem to be required, eg. deleting node. There might be a need of removing sre02 node with `reset_nodes=false` but it looks like it's already done manually.

Sure, I will write what should be done according this scenario:
https://github.com/kubernetes-sigs/kubespray/blob/master/docs/nodes.md#addingreplacing-a-master-node

> Need details of the process in JIRA ticket.

Sure, I will fill in the details in jira. Just keep in mind that this will change in cane some further steps / different approach is needed.

**Comment by gh-lbulawa** [comment]
Also general comment: we might want to learn managing cluster using kubespray instead of doing stuff manually.

**Comment by gh-lbulawa** [comment]
Closing. Cluster was tore down and bootstraped from scratch therefore it's no longer needed.

**Pull request closed without merging**
